spring:
  application:
    name: escuela
  datasource:
    url: jdbc:mySql://${DB_HOST}:3306/${DB}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${USER}
    password: ${PASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/
